# Generated by Django 5.2.12 on 2026-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteorm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteorm',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
